name: Run Integration Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  Integration test - Communication Socket:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Integration test - Communication Socket
        run: python -m unittest discover -s tests/integration -p 'test_communication_socket.py'

  Integration test - Sensor:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Integration test - Sensor
        run: python -m unittest discover -s tests/integration -p 'test_sensor.py'

  Integration test - Subscriber:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Integration test - Subscriber
        run: python -m unittest discover -s tests/integration -p 'test_subscriber.py'

  Integration test - Message Broker:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Integration test - Message Broker
        run: python -m unittest discover -s tests/integration -p 'test_message_broker.py'

  Integration test - Overall Scenarios:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Integration test - Overall Scenario
        run: python -m unittest discover -s tests/integration -p 'test_overall_scenario.py'